version: '3'

services:
  chess-app:
    image: chess-app:01
    ports:
      - "8080:8080"
      - "8081:8081"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - chessnetwork
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - chessnetwork
networks:
  chessnetwork:
    driver: bridge
