version: '3'

services:
  chess:
    image: chess:01
    ports:
      - "8081:8081"
    links:
      - mongodb
    networks:
      - chessnetwork
  chesscl:
    image: chesscl:01
    ports:
      - "8080:8080"
    depends_on:
      - chess
    networks:
      - chessnetwork
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - chessnetwork
networks:
  chessnetwork:
    driver: bridge
